---
deployment:
  tasks:
<<<<<<< HEAD
    - export DEPLOYPATH=/home/fhvy075qb2xc/public_html
    - /bin/cp -a * $DEPLOYPATH
=======
    - export DEPLOYPATH=/home/fhvy075qb2xc/
    - /bin/cp -R /home/fhvy075qb2xc
>>>>>>> e0cce10bfd6bb1bbad1c111ed6e9c5c1f30adbd3
